name: Evaluate Predictions in Production

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  evaluate-in-production:
    runs-on: ubuntu-latest

    outputs:
      sha_new: ${{ steps.sha_new.outputs.SHA_NEW }}

    permissions:
      contents: write

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install pandas dvc[s3] pymongo python-dotenv scikit-learn

      - name: Authenticate dvc remote
        run: |
          dvc remote modify origin --local access_key_id "${{ secrets.DVC_ACCESS_KEY_ID }}"
          dvc remote modify origin --local secret_access_key "${{ secrets.DVC_SECRET_ACCESS_KEY }}" 

      - name: Pull data from dvc
        run: dvc pull

      - name: Evaluate travel times
        run: |
          cd src/models/travel_times
          python evaluate_prod.py

      - name: Evaluate vehicle counters
        run: |
          cd src/models/vehicle_counters
          python evaluate_prod.py